import type { Metadata } from "next";
import { Geist, Geist_Mono, PT_Serif, Cormorant } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const ptSerif = PT_Serif({
    variable: "--font-pt-serif",
    subsets: ["latin"],
    weight: ["400", "700"], // Specify weights you need
});

const cormorant = Cormorant({
    variable: "--font-cormorant",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"], // Choose weights you need
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ptSerif.variable} {${cormorant.variable}}  antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
